# Generated by Django 4.2.3 on 2023-07-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion7', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('fecha', models.EmailField(max_length=254)),
            ],
        ),
    ]
