# Generated by Django 4.2.1 on 2023-07-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion7', '0004_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tema',
            field=models.CharField(max_length=500),
        ),
    ]
